apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassistant-data
  namespace: homeassistant
  labels:
    app: homeassistant-label
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
