apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    keel.sh/policy: all
    keel.sh/pollSchedule: '@every 5m'
    keel.sh/trigger: poll
  name: z2m
  namespace: homeassistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: z2m
  template:
    metadata:
      labels:
        app: z2m
    spec:
      containers:
      - name: z2m
        image: koenkk/zigbee2mqtt:1.39.0
        env:
          - name: TZ
            value: Europe/Belgrade
          - name: ZIGBEE2MQTT_CONFIG_MQTT_SERVER
            value: "mqtt://mosquitto-service.homeassistant.svc.cluster.local:8883"
          - name: ZIGBEE2MQTT_CONFIG_MQTT_USER
            value: "mqtt-user"
          - name: ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD
            value: "password"
          - name: ZIGBEE2MQTT_CONFIG_HOMEASSISTANT
            value: "true"
        securityContext:
          privileged: true
        ports:
          - containerPort: 8080
        volumeMounts:
          - name: z2m-data
            mountPath: /app/data
          - name: z2m-udev
            mountPath: /run/udev
          - name: ttyacm
            mountPath: /dev/ttyACM0
        resources:
          requests:
            memory: 256Mi
            cpu: 100m
          limits:
            memory: 1Gi
            cpu: 1
      volumes:
        - name: z2m-data
          persistentVolumeClaim:
            claimName: z2m-data
        - name: z2m-udev
          hostPath:
            path: /run/udev
        - name: ttyacm
          hostPath:
            path: /dev/ttyACM0

